replicaCount: 1

image:
  repository: ghcr.io/home-assistant/home-assistant
  tag: stable
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8123

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi

persistence:
  enabled: true
  size: 2Gi
  storageClass: ""

ingress:
  enabled: true

env: []
