replicaCount: 1

image:
  repository: adguard/adguardhome
  tag: v0.107.52
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  httpPort: 3000
  dnsPort: 53

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

persistence:
  enabled: true
  size: 1Gi
  storageClass: ""

ingress:
  enabled: true
