apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homeassistant
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hxteam24-lab/demo-argo.git
    targetRevision: main
    path: charts/homeassistant
    helm:
      valueFiles:
        - ../../values/homeassistant-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: homeassistant
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
