apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-ha-config
  namespace: {{ .Release.Namespace }}
data:
  configuration.yaml: |
    homeassistant:
      name: Home
      unit_system: metric
    http:
      use_x_forwarded_for: true
      trusted_proxies:
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
        - 127.0.0.0/8
