replicaCount: 1

image:
  repository: nextcloud
  tag: "30.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi

persistence:
  enabled: true
  size: 5Gi
  storageClass: ""

ingress:
  enabled: true
  trustedDomain: "10.241.40.167"

env:
  - name: NEXTCLOUD_ADMIN_USER
    value: admin
  - name: NEXTCLOUD_ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: nextcloud-admin
        key: password
  - name: SQLITE_DATABASE
    value: nextcloud
  - name: NEXTCLOUD_TRUSTED_DOMAINS
    value: "10.241.40.167 localhost"
  - name: OVERWRITEWEBROOT
    value: "/cloud"
  - name: OVERWRITEPROTOCOL
    value: "http"
